using Microsoft.EntityFrameworkCore;
using Payroll.Application.Common.Interfaces;
using QuestPDF.Fluent;
using QuestPDF.Helpers;

namespace Payroll.Infrastructure.Services;

public class TaxCertificatePdfService(IAppDbContext db) : ITaxCertificatePdfService
{
    public async Task<byte[]> GenerateAsync(Guid certificateId, CancellationToken ct = default)
    {
        var c = await db.EmployeeTaxCertificates.Include(x => x.Employee).ThenInclude(e => e.Company)
            .Include(x => x.TaxYear).Include(x => x.Lines).FirstOrDefaultAsync(x => x.Id == certificateId && !x.IsDeleted, ct)
            ?? throw new InvalidOperationException("Tax certificate not found.");
        return Document.Create(container => container.Page(page =>
        {
            page.Size(PageSizes.A4); page.Margin(35); page.DefaultTextStyle(x => x.FontSize(10));
            page.Header().Column(col => { col.Item().Text(c.Company.Name).FontSize(18).Bold(); col.Item().Text("Employee Tax Certificate (draft software output)").FontSize(13); col.Item().Text($"Tax year: {c.TaxYear.Name}"); });
            page.Content().Column(col =>
            {
                col.Item().PaddingVertical(12).Text($"Employee: {c.Employee.FirstName} {c.Employee.LastName} ({c.Employee.EmployeeNumber})").Bold();
                col.Item().Text($"Certificate number: {c.CertificateNumber}");
                col.Item().PaddingTop(12).Table(table =>
                {
                    table.ColumnsDefinition(columns => { columns.RelativeColumn(3); columns.RelativeColumn(1); });
                    table.Header(header => { header.Cell().Text("SARS code / description").Bold(); header.Cell().AlignRight().Text("Amount").Bold(); });
                    foreach (var line in c.Lines) { table.Cell().Text($"{line.SARSCode} - {line.Description}"); table.Cell().AlignRight().Text($"R {line.Amount:N2}"); }
                });
                col.Item().PaddingTop(15).Text($"Gross remuneration: R {c.GrossRemuneration:N2}");
                col.Item().Text($"Taxable income: R {c.TaxableIncome:N2}");
                col.Item().Text($"PAYE: R {c.PAYE:N2}    UIF: R {c.UIF:N2}    SDL: R {c.SDL:N2}");
                col.Item().PaddingTop(15).Text("This document is generated by Payroll SA for review and is not currently claimed to be an officially SARS-compliant certificate.").Italic();
            });
            page.Footer().AlignCenter().Text("Payroll SA");
        })).GeneratePdf();
    }
}