<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>

    <!-- Excel -->
    <PackageReference Include="ClosedXML" Version="0.105.1" />

    <!-- Hangfire -->
    <PackageReference Include="Hangfire.AspNetCore" Version="1.8.24" />
    <PackageReference Include="Hangfire.Core" Version="1.8.24" />
    <PackageReference Include="Hangfire.InMemory" Version="1.0.0" />

    <!-- Email -->
    <PackageReference Include="MailKit" Version="4.17.0" />

    <!-- ASP.NET Core Identity / Authentication -->
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.10" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="9.0.10" />

    <!-- Entity Framework Core -->
    <PackageReference Include="Pomelo.EntityFrameworkCore.MySql" Version="9.0.0" />

    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="9.0.10">
      <IncludeAssets>
        runtime; build; native; contentfiles; analyzers; buildtransitive
      </IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>

    <!-- PDF -->
    <PackageReference Include="QuestPDF" Version="2026.7.2" />

    <!-- Logging -->
    <PackageReference Include="Serilog.AspNetCore" Version="10.0.0" />
    <PackageReference Include="Serilog.Sinks.File" Version="7.0.0" />

    <!-- JWT -->
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.22.0" />

  </ItemGroup>

  <ItemGroup>

    <ProjectReference Include="..\Payroll.Application\Payroll.Application.csproj" />
    <ProjectReference Include="..\Payroll.Domain\Payroll.Domain.csproj" />
    <ProjectReference Include="..\Payroll.Shared\Payroll.Shared.csproj" />

  </ItemGroup>

</Project>